Sys.setenv(
  CB_SITE_CSV_URL = "<INSERT YOUR TEST SITE CSV URL HERE>",
  CB_SITE_NESTED_RDS_URL = "<INSERT YOUR TEST SITE NESTED RDS URL HERE>",
  CB_PERSONAL_CSV_URL = "<INSERT YOUR TEST PERSONAL CSV URL HERE>",
  CB_PERSONAL_DOWNLOAD_JPG_URL = "<INSERT YOUR TEST PERSONAL DOWNLOAD URL HERE>"
)
